Biomphalaria_straminea and Achatina_immaculata
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Achatina_immaculata.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Achatina_immaculata.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Achatina_immaculata.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Achatina_immaculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Biomphalaria_glabrata
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Biomphalaria_glabrata.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_glabrata.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_glabrata.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Biomphalaria_glabrata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Chrysomallon_squamiferum
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Chrysomallon_squamiferum.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Chrysomallon_squamiferum.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Chrysomallon_squamiferum.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Chrysomallon_squamiferum --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Crassostrea_gigas
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Crassostrea_gigas.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Crassostrea_gigas.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Crassostrea_gigas.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Crassostrea_gigas --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Cyclina_sinensis
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Cyclina_sinensis.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Cyclina_sinensis.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Cyclina_sinensis.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Cyclina_sinensis --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Haliotis_rubra
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Haliotis_rubra.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Haliotis_rubra.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Haliotis_rubra.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Haliotis_rubra --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Magallana_hongkongensis
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Magallana_hongkongensis.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Magallana_hongkongensis.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Magallana_hongkongensis.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Magallana_hongkongensis --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Marisa_cornuarietis
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Marisa_cornuarietis.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Marisa_cornuarietis.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Marisa_cornuarietis.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Marisa_cornuarietis --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Octopus_sinensis
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Octopus_sinensis.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Octopus_sinensis.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Octopus_sinensis.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Octopus_sinensis --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Pinctada_fucata_martensii
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Pinctada_fucata_martensii.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Pinctada_fucata_martensii.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Pinctada_fucata_martensii.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Pinctada_fucata_martensii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Pomacea_canaliculata
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Pomacea_canaliculata.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Pomacea_canaliculata.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Pomacea_canaliculata.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Pomacea_canaliculata --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
Biomphalaria_straminea and Scapharca_Anadara_broughtonii
Rscript /jelly_data/yichun/scripts/2synteny/orthofinder_synteny_plot_ortho_frag_significance_longgtf.R --input ortholog.Biomphalaria_straminea__v__Scapharca_Anadara_broughtonii.tsv.txt --xspecies-fai /jelly_data/yichun/snail/fai/Biomphalaria_straminea.fa.fai --yspecies-fai /jelly_data/yichun/snail/fai/Scapharca_Anadara_broughtonii.fa.fai --xspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Biomphalaria_straminea.longest-gene.gtf --yspecies-gtf /jelly_data/yichun/snail/gtf/formatted.Scapharca_Anadara_broughtonii.longest-gene.gtf --xspecies-name Biomphalaria_straminea --yspecies-name Scapharca_Anadara_broughtonii --min-orthologs-x 20 --min-orthologs-y 5 --plot-size 15 --break-size 50
